### ISSUE TITLE
Definition of TransposedLinear module

### ISSUE THREAD

**Issue by changmin-yu** [mackelab/neural_timeseries_diffusion#1]
Hi, 
Thanks for the great work and for sharing the codebase. I am currently going through the code, and I noticed the missing of the definition of TransposedLinear module used here: https://github.com/mackelab/neural_timeseries_diffusion/blob/85d93743259d87924cc0934a56714cdcf5d095d9/ntd/modules.py#L94
I am curious to learn the definition of this module, my hypothesis is that this is a linear mapping from flattened input to a reshaped input cohering with the out_channel:  (B, in_C*T) -> (B, out_C*T) -> (B, out_C, T). 
Thanks!

**Comment by jsvetter** [comment]
Hi,

good catch! This was a deprecated function due to this now fixed PyTorch issue [here](https://github.com/pytorch/pytorch/issues/107876).

The transposed linear layer applied a linear layer to the channel dimension after transposing, i.e, `(B, in_C, T) -> (B, T, in_C)`. 
The same operation is now performed with a `kernel_size=1` convolution instead.

Thanks for finding this! :)
